### PR TITLE
prevent private notes from being sent to redmine

### PR DESCRIPTION
**Pull request by thanosk**

### CODE REVIEW

**Comment by brother** [comment]
Seems more like a setting (active by default) than something this harsh. If everyone in the target channel have access to the private note it does not make sense to not allow it to pass.

**Comment by thanosk** [comment]
Perhaps I'm wrong, but aren't private notes supposed to be invisible to all (even admins and managers) except their (one and only) author? If that's the case, there is never a list of users that have access to these notes.

**Comment by brother** [comment]
gee. you are correct! didn't even think you that part... that's how often I use private notes =)

**Comment by brother** [comment]
admins can see them but not normal users I guess.

**Comment by sciyoshi** [comment]
:+1: thank you @thanosk for the fix!

**Pull request merged**
